### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by ayumyonn** [ayumyonn/20240721#25]
### 実装予定の機能

- [ ] Postの新規投稿機能
- [ ] Postの一覧機能
- [ ] ユーザーの新規登録機能
- [ ] ログイン機能
- [ ] ログアウト機能

### 必要なページ

- [ ] トップページ(Post一覧)
- [ ] Post新規投稿ページ
- [ ] ユーザー新規登録ページ
- [ ] ログインページ

**Comment by Tsuchiya2** [comment]
![image](https://github.com/user-attachments/assets/c42ad66f-a74d-40d0-8388-b9781069e784)

projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。上記確認できる状態で再提出をお願いいたします。

**Comment by ayumyonn** [comment]
"Issueベースの開発"レビュー依頼はこちらのURLでご確認いただけるかと思います。
看板、issue、ストーリーポイントはこちらからご確認いただけると思います。よろしくお願い致します。
https://github.com/users/ayumyonn/projects/5/views/1

**Comment by Tsuchiya2** [comment]
上記URLから確認できました。
ストーリーポイントが振られていないカードが散見されましたので、全てのカードのストーリーポイントを付与した状態での提出をお願いいたします。

**Comment by ayumyonn** [comment]
https://github.com/users/ayumyonn/projects/5/views/1
issueのものはストーリーポイント付けました。ご確認お願いします。

**Comment by Tsuchiya2** [comment]
- sorceryの導入（ユーザー新規登録機能）
- (必要な場合)config/application.rbの編集

↑issueになっていますが、ストーリーポイントが付いていないようです。ご確認ください。

<img width="848" alt="image" src="https://github.com/user-attachments/assets/dd0a3339-aa87-4866-bb50-b7ef92d0d582">

**Comment by ayumyonn** [comment]
https://github.com/users/ayumyonn/projects/5/views/1

**Comment by shota-hope** [comment]
LGTMです。
(再レビューをお願いするときは、コメントを添えると良いと思います！)
