### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by ayumyonn** [ayumyonn/20240721#55]
## 各種情報
サービス名: お気に入り店舗管理サービス
サービスURL:  https://infinite-plateau-85381-1b0b6cafa557.herokuapp.com/login

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ログイン機能
- [x]  ユーザー登録機能

-  post新規投稿機能 (名前、住所、w/、★、感想、ジャンル、写真)

-  リマインド機能(3日後から記録可能になる感想、評価の機能)

## READMEレビュー時から変更した機能

- post新規投稿機能 の内容を名前、ユーザー名、感想、写真に変更し、実装しました。

- 感想入力のリマインド機能はMVPリリース後実装予定です。
## サービスイメージがわかるようなスクリーンショット等

<img width="1440" alt="スクリーンショット 2024-08-01 15 38 22" src="https://github.com/user-attachments/assets/1f95b21c-86bf-4001-91dc-9e918ced4789">
<img width="1440" alt="スクリーンショット 2024-08-01 15 38 55" src="https://github.com/user-attachments/assets/87db958c-0ddb-4ef9-8332-bd446844cfda">
<img width="1440" alt="スクリーンショット 2024-08-01 15 39 52" src="https://github.com/user-attachments/assets/3d860351-f080-4315-93da-03060f9646e1">
<img width="1440" alt="スクリーンショット 2024-08-01 15 40 24" src="https://github.com/user-attachments/assets/6fb1da88-24ec-4a88-a1dc-f14af390899e">
<img width="1440" alt="スクリーンショット 2024-08-01 15 40 47" src="https://github.com/user-attachments/assets/c94d9f0d-7c19-40fd-b2c0-9068db30929b">
<img width="1440" alt="スクリーンショット 2024-08-01 15 42 02" src="https://github.com/user-attachments/assets/7dbfcc6e-d476-44e0-b0e3-545e29cf2f26">
<img width="1440" alt="スクリーンショット 2024-08-01 15 42 28" src="https://github.com/user-attachments/assets/bfd9fcb1-b299-4860-b018-1d6fe2fe9aca">

**Comment by ayumyonn** [comment]
お疲れ様です。
すみません、デプロイしたのですが、ログイン画面からユーザー登録画面に行くとエラーが起こり対処できず、
本日卒業日のためそのままで提出させていただきました。すみません。
スクリーンショットが現段階の実装内容です。

**Comment by kenchasonakai** [comment]
デプロイされているアプリ上で機能の確認が出来ないとレビューできませんので動作するようにしてから再度ご提出をお願いいたします

**Comment by ayumyonn** [comment]
アプリ上で確認いただけるかと思います。よろしくお願いいたします。

**Comment by kenchasonakai** [comment]
LGTMです！
